<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Prashant" failures="0" tests="4" name="com.javaPractice.javaPractice.Power_Of_Given_Number" time="0.023" errors="0" timestamp="2024-01-30T23:00:21 IST" skipped="0">
  <testcase classname="com.javaPractice.javaPractice.Power_Of_Given_Number" name="power_Of_Given_Number_Using_For_Loop" time="0.018"/>
  <system-out/>
  <testcase classname="com.javaPractice.javaPractice.Power_Of_Given_Number" name="power_Of_Given_Number_Using_While_Loop" time="0.002"/>
  <system-out/>
  <testcase classname="com.javaPractice.javaPractice.Power_Of_Given_Number" name="power_Of_Given_Number_Using_Recursion" time="0.001"/>
  <system-out/>
  <testcase classname="com.javaPractice.javaPractice.Power_Of_Given_Number" name="power_Of_Given_Number_Using_MathPow_Method" time="0.002"/>
  <system-out/>
</testsuite> <!-- com.javaPractice.javaPractice.Power_Of_Given_Number -->
